doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: enroot_gc
                user: 'enroot_gc_user'
                password: '2Fnv-_NjK?cM?K+&xV'
                host: enroot-wp-rds.ckxt1cihzayi.ap-south-1.rds.amazonaws.com
                #user: 'root'
                #password: ''
                #host: localhost
                driver: 'pdo_mysql'
                server_version: '8.0.17'
                default_table_options:
                charset: utf8mb4
                mapping_types:
                    enum: string
            #                url: '%env(resolve:DATABASE_URL)%'


    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                dql:
                    datetime_functions:
                        DAY: DoctrineExtensions\Query\Mysql\Day
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                mappings:
                    Admin:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: default
